# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_edwlan age1rqzmdt6jgxqxutfc2de576eatk58f8tvf8t6h0rgpgh647t974fsrvmlaa
creation_rules:
  - path_regex: .*/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_edwlan
