setopt allexport
setopt autocd
setopt autolist
setopt autopushd
setopt cdablevars
setopt completeinword
setopt extended_glob
setopt histexpiredupsfirst
setopt histignorealldups
setopt histverify
setopt listpacked
setopt markdirs
setopt nobeep
setopt nobgnice
setopt nochaselinks
setopt promptsubst
setopt pushdignoredups
setopt sharehistory

export SAVEHIST=10000000
export HISTSIZE=10000000
export HISTFILE=$HOME/.zshistory
