setopt allexport
setopt autocd
setopt autolist
setopt autopushd
setopt nobeep
setopt cdablevars
setopt nochaselinks
setopt completeinword
setopt histexpiredupsfirst
setopt histignorealldups
setopt histverify
setopt listpacked
setopt markdirs
setopt nobgnice
setopt promptsubst
setopt pushdignoredups
setopt sharehistory

export SAVEHIST=10000000
export HISTSIZE=10000000
export HISTFILE=$HOME/.zshistory
