#!/usr/bin/zsh

chosen=`mpc playlist -f "[%position%: %artist% - %album% - %title%]" | menu | cut -d: -f 1`
(( target=(`mpc current -f "[%position%]"` + 1) ))

if [[ "$chosen" -ne "" ]]; then
  mpc move $chosen $target
fi

