#!/usr/bin/env zsh

if git remote | grep origin; then
  git push --all "$@" origin
  git push --tags origin
fi

git remote | grep -v origin | (
    while read -r remote; do
	printf "Pushing to %s\n" "$remote..."
	git push --all "$@" "$remote"
	git push --tags "$remote"
    done
)
