#!/usr/bin/env python2

import goose
import lxml
import argparse

p = argparse.ArgumentParser()
p.add_argument('url')
args = p.parse_args()

g = goose.Goose()
a = g.extract(args.url)
print lxml.html.tostring(a.doc)
