#!/usr/bin/python -u
from __future__ import print_function

import heapq

def file_iter(fil):
    line = 0
    while line != '':
        line = fil.readline()
        yield line

def sorter(gen, len_):
    buffer = []

    for line in gen:
        heapq.heappush(buffer, line)
        if len(buffer) == len_:
            yield heapq.heappop(buffer)

if __name__ == '__main__':
    import sys
    for line in sorter(file_iter(sys.stdin), 10):
        print('>', line, end='')
