#!/usr/bin/env zsh

dot -Gbgcolor=$(zenburn --html bg+1) \
    -Gpad=0.5,0.25 \
    -Nfontcolor=$(zenburn --html fg) \
    -Ncolor=$(zenburn --html yellow) \
    -Nshape=box \
    -Ecolor=$(zenburn --html fg) \
    -Grankdir=LR \
    -Gsplines=ortho \
    -Gsize=15,15\! \
    -Gdpi=50
