#!/usr/bin/env zsh

dot -Gbgcolor="$(zenburn --hsv bg+1)" \
    -Gpad=0.5,0.25 \
    -Gconcentrate=true \
    -Gsplines=ortho \
    -Nfontcolor="$(zenburn --hsv fg)" \
    -Nshape=box \
    -Ecolor="$(zenburn --hsv fg)" \
    -Grankdir=LR \
    -Gsize=15,15\! \
    -Gdpi=50
