#!/bin/zsh
export PATH=$HOME/bin:$PATH
 
# Load resources
 
xrdb -merge $HOME/.Xresources

# Set the background color<
 
xsetroot -solid black
xsetbg $HOME/.xmonad/cheatsheet.png
if [ -e $HOME/Pictures/backgrund.png ]; then
   xloadimage -onroot -quiet $HOME/Pictures/background.png
fi
conky -bd

xscreensaver -no-splash &
 

# Set up an icon tray
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x000000 --height 17 &
synergys
 
# notifications

dunst &

# dropbox

dropbox start &
btsync

# notes

tomboy &
 
# mixer

qasmixer -t &

# Fire up apps
 

$HOME/github_repos/shairport/shairport -a srv2 -o pulse -d | swap_variable SHAIRPORT_PID

sonata --hidden &
 
if [[ -x /usr/bin/nm-applet ]] ; then
   nm-applet --sm-disable &
fi
 
eval `ssh-agent`
exec xmonad
