#!/bin/zsh
export PATH=$HOME/bin:$PATH
export LD_LIBRARY_PATH=/home/edwlan/gtk-git/inst/lib/:/home/edwlan/lib:$LD_LIBRARY_PATH
#xrandr --output HDMI-0 --mode 1920x1200 --left-of VGA-0
#xrandr --output HDMI-0 --primary
#xrandr --output VGA-0 --mode 1024x768

# Load resources

xrdb -merge $HOME/.Xresources
xmodmap $HOME/.xmodmap

# Set the background color<

xsetroot -solid black
xsetbg $HOME/.xmonad/cheatsheet.png
if [ -e $HOME/Pictures/backgrund.png ]; then
   xloadimage -onroot -quiet $HOME/Pictures/background.png
fi
conky -bd

xscreensaver -no-splash &


# Set up an icon tray
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x000000 --height 17 &
synergys

# notifications

dunst &

# dropbox

dropbox start &
btsync

# notes

tomboy &

# mixer

qasmixer -t &

# Fire up apps


$HOME/github_repos/shairport/shairport -a srv2 -o pulse -d | swap_variable SHAIRPORT_PID

sonata --hidden &

if [[ -x /usr/bin/nm-applet ]] ; then
   nm-applet --sm-disable &
fi

gnome-settings-daemon &
eval `gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh`
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_PID


exec ssh-agent /home/edwlan/bin/stumpwm
#exec xmonad
