#!/bin/sh
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/yeganesh_run
else
	cache=$HOME/.yeganesh_cache # if no xdg dir, fall back to dotfile in ~
fi
(
	IFS=:
	if stest -dqr -n "$cache" $PATH; then
		stest -flx $PATH | sort -u | tee "$cache" | /home/edwlan/.local/bin/yeganesh "$@"
	else
		/home/edwlan/.local/bin/yeganesh "$@" < "$cache"
	fi
) | ${SHELL:-"/bin/sh"} &
